pipeline {
   agent any
   
   stages {
   
      stage('Downloading from jfrog repository') {
         
         steps {
         	
         	rtServer (
                id: 'jenkins-artifactory-id'
            )
         	rtDownload (
	    		serverId: 'jfrog',
	    		spec: '''{
	          		  "files": [
		            	{
	              			"pattern": "gradle-dev-local/com/fabianorapkiewicz/cloudnative/tema6/tema-06/1.0/",
	              			"target": "artifactory/bin/"
	            		}
	          		  ]
	    		}''',
	    		
	    		buildName: 'calculator-tema06',
	    		buildNumber: '06'
			)
         }
      }
      
      stage('Building docker image and push docker hub') {
          
          steps {
              sh 'packer build build-image.json'
          }
      }

   }
}