pipeline {
   agent any
   
   stages {
   
      stage('Downloading from jfrog repository') {
         
         steps {
         	
         	rtServer (
                id: 'jenkins-artifactory-id'
            )
         	rtDownload (
	    		serverId: 'jfrog',
	    		spec: '''{
	          		  "files": [
		            	{
	              			"pattern": "gradle-dev-local/com/fabianorapkiewicz/cloudnative/tema6/tema-06/",
	              			"target": "cloud-final1/"
	            		}
	          		  ]
	    		}''',
	    		
	    		buildName: 'calculator-tema06',
	    		buildNumber: '06'
			)
         }
      }
   }
}