---

- name: Provision Python
  hosts: localhost
  gather_facts: no
  tasks:

    - name: install java 8
      apt:
        name: openjdk-8-jdk
        update_cache: yes
        install_recommends: no